server:
  port: 5432


spring:
  datasource:
    username: system
    password: akash
    url: jdbc:oracle:thin:@localhost:1521:orcl
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.Oracle12cDialect
    show-sql: true
  application:
    name: HOTEL-SERVICE

  config:
    import:
      optional:configserver:http://localhost:0987

eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7654/eureka


